name: fc24_coach_ai
description: FC24 Coach AI mobile app safe start
publish_to: "none"
version: 1.0.4+4

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
